### ISSUE TITLE
Cycle Detection Feature Implementation: Resolving Bugs and Enhancements

### ISSUE THREAD

**Issue by palfner-sse** [e-Learning-by-SSE/nm-self-learning#100]
# Background Information
Cycle detection, as outlined in issue #68, has been successfully implemented. However, as we approach the final stages of this feature, we have identified several lingering bugs that require attention. Additionally, while working with the Editor, we encountered some issues unrelated to #68. This issue is created after an agreement from the weekly meeting with @spark-sse . 

## List of Identified Bugs
1. [x] Deleting a skill that is part of a cycle results in the re-appearance of coloring for skills associated with the cycle or its path when selecting them.
2. [x] Adding a child or parent to a skill reflects the change in the UI but doesn't update the database.
3. [ ] Deleting a skill or folder located at the first level (depth of 0) removes the skill from the database but not from the UI. Moreover, the UI freezes during this operation, rendering further actions impossible.
4. [ ] When a cycle is present, users can infinitely expand the folder within the cycle.
5. [ ] Upon discovering a cycle, the folders containing it should be expanded to provide users with visibility into where the cycle exists.
6. [ ] Searching for a skill does not automatically expand the folders to display the skill. Skills without a depth of 0 are not found in the search.
7. [ ] When adding a Parent to a Skill the UI does not update but  the changes are saved to the Database

**Comment by spark-sse** [comment]
Blocked due to refactoring. Bugs will be reviewed after finished refactoring see #94
