### ISSUE TITLE
Einziger Autor einer Lerneinheit oder eines Kurses kann entfernt werden

### ISSUE THREAD

**Issue by ganskem** [e-Learning-by-SSE/nm-self-learning#120]
### Problembeschreibung

Wenn eine Lerneinheit oder ein Kurs nur einen Autor hat (s. Bild 1), kann dieser im Editor für Lerneinheiten oder Kurse entfernt werden. Nach dem Entfernen (s. Bild 2, Bild 3)) und anschließenden Speichern hat die Lerneinheit oder der Kurs keinen Autor mehr und kann daher nicht mehr bearbeitet werden.

**Fall: Lerneinheit**

Wenn eine Lerneinheit, für die man der einzige Autor gewesen ist, zuvor einem Kurs hinzugefügt wurde, erscheint beim Versuch, sie zu bearbeiten, eine Meldung, dass man nicht über die nötigen Berechtigungen verfügt (s. Bild 5). Der Dialog zeigt zudem an, dass die Lerneinheit keinen Autor mehr hat.

**Fall: Kurs**

Ein Versuch, den Kurs zu speichern, führt zu einer Fehlermeldung, die besagt, dass man keine Zugriffsrechte für die Seite hat (s. Bild 4).

### Lösungsvorschlag

Es sollte nicht möglich sein, den einzigen Autor einer Lerneinheit oder eines Kurses zu entfernen. Falls nur ein Autor existiert, sollte das Symbol zum Löschen (Kreuz) ausgeblendet werden. Das Entfernen von Autoren sollte erst möglich sein, nachdem der Lerneinheit oder dem Kurs mindestens zwei Autoren zugewiesen wurden.

### Bilder zur Erklärung

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/ac2cda2d-e837-46f0-a5c7-03faf51fcd53)
_Bild 1: Autoren-Bereich mit einzelnem Autor_

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/fe93a13a-17f2-4a06-a279-67b21ecc15c9)
_Bild 2: Confirmation Dialog_

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/e1f56dc9-7895-427d-bbe4-43463859c944)
_Bild 3: Autoren-Bereich ohne Autor_

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/24ad77d7-0cfc-4552-baf9-0ef0d4b21ad2)
_Bild 4: Verhalten nach Speichern der Änderungen in einem Kurs_

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/1b230c96-a5ed-4943-a70d-041fc6d40288)
_Bild 5: Dialog beim versuchten Öffnen einer Lerneinheit, in der man zuvor Autor gewesen ist._

**Comment by spark-sse** [comment]
Lösungsvorschlag kann so umgesetzt werden. Der letzte Autor einer Lerneinheit darf nicht entfernt werden (ggf. Außnahme für Admins).

**Comment by palfner-sse** [comment]
Wie wichtig ist die Ausnahme für Admins? Das macht es auf jeden Fall erheblich aufwändiger.
