### ISSUE TITLE
Kurse in denen alle Lerneinheiten abgeschlossen wurden lassen sich nicht erneut öffnen

### ISSUE THREAD

**Issue by ganskem** [e-Learning-by-SSE/nm-self-learning#134]
### Problembeschreibung

Der "Fortfahren"-Button springt bei einem nicht vollständig bearbeiteten Kurs zur als nächstes zu bearbeitenden Lerneinheit. Sobald die letzte Lerneinheit abgeschlossen wurde springt der Fortschrittsbalken in der Lernansicht auf 100%. Beim Öffnen der Kursübersicht erscheint weiterhin der "Fortfahren"-Button. Beim Klicken wird ein 404-Fehler angezeigt.

**Bilder**

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/31200fa9-09c5-497a-aa81-574ef32bc158)
_Kursübersicht eines nicht vollständig bearbeiteten Kurses_

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/799a7d41-9d43-43a8-aea5-574178081942)
_Lernansicht nach Abschluss der letzten Lerneinheit_

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/93f5e942-effd-4616-9d80-7ef312bea242)
_Kursübersicht eines abgeschlossenen Kurses_

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/56004b5c-b7fe-4634-82a9-ee2ed1732970)
_404-Fehler nach Klicken auf den "Fortfahren"-Button_

### Lösungsvorschläge zur Diskussion

- Umbenennen des "Fortfahren"-Button in "Öffnen" nach Abschluss des Kurses. 
- Weiterleiten zur ersten Einheit des Kurses
- Ein Ansehen der Lerninhalte sollte weiterhin möglich sein. Ein Erneutes Bearbeiten der Lernkontrollen vermutlich nicht.

**Comment by spark-sse** [comment]
> Ein Ansehen der Lerninhalte sollte weiterhin möglich sein. Ein Erneutes Bearbeiten der Lernkontrollen vermutlich nicht.
"vermutlich"?. Unklare requirements. Wann soll eine Lernkontrolle wieder möglich sein? 
Wenn zb etwas an der Lerneinheit geändert wird? 

Ich denke man kann erstmal die Nutzer die Lernkontrollen auch erneut belegen lassen, wenn sie den Kurs erneut starten wollen. 
Der Button würde dann auch nicht "Öffnen" heißen, sondern "Erneut Starten"
