### ISSUE TITLE
[LTB] Lernenden-Dashboard

### ISSUE THREAD

**Issue by ganskem** [e-Learning-by-SSE/nm-self-learning#155]
Lernende erhalten ein Dashboard um zu verschiedenen Bereichen der Lernplattform zu gelangen, die für das eigene Lernen relevant sind. Die angezeigten Inhalte sind dabei sowohl vom eigenen Lernen als auch von gewählten Einstellungen (vgl. #154) abhängig. Das Dashboard enthält die folgenden Elemente:

1. Zuletzt bearbeiteter Kurs
2. Zuletzt bearbeitete Lerneinheiten
3. Navigation zur Übersicht der selbst belegten Kurse
4. Navigation zur Übersicht des Lerntagebuchs
5. Navigation zu den Learning Analytics
6. Navigation zum Editor für Lernziele

Zu beachten ist hierbei, dass Punkte 1 - 3 für alle Studierende, unabhägig von gewählten Einstellungen, zu sehen sind. Die Learning Analytics (5.) sind nur dann verfügbar, wenn Studierende ihr Einverständnis für das Sammeln von Daten zum Lernverhalten gegeben haben (vgl. #154). Das Lerntagebuch (4.) ist nur dann verfügbar, wenn Studierende dies in den Einstellungen aktiviert haben (vgl. #154). Auch die Lernziele sind gekoppelt mit dem Lerntagebuch.

![Image](https://github.com/e-Learning-by-SSE/nm-concept/assets/118170487/2fd3a1ad-dd87-4b5f-85c2-e2a535a6a4fb)

Oben links: letzter bearbeiteter Kurs
Daneben: zuletzt bearbeitete Lerneinheiten (vgl. aktuelle Übersicht)

![Image](https://github.com/e-Learning-by-SSE/nm-concept/assets/118170487/1d9853b4-ae42-4426-9cd8-08bc47371185)

Info-Icon wurde angeklickt. Dialogfenster öffnet sich (vgl. #154). Studierende werden über den Umgang mit Daten informiert.

![Image](https://github.com/e-Learning-by-SSE/nm-concept/assets/118170487/c48eb9ec-1d8b-4199-9500-eda62ec6abcc)

Beide Einstellungen werden aktiviert.

![Image](https://github.com/e-Learning-by-SSE/nm-concept/assets/118170487/bca6ca4a-26c5-4bed-b809-59c49db6083d)

Lernstatistik, Lerntagebuch und Lernziele sind freigeschaltet.

Video:

https://youtu.be/b4uZrsca8p8?si=1MTiJ9EOTQ5wfizV

**Comment by spark-sse** [comment]
*Weitere ideen*:
- der name des aktuellen nutzer oben anziegen (so wie im vorherigen dashboard)

**Comment by spark-sse** [comment]
Außerdem wäre es gut ein Button zu haben der direkt die Metriken / das LTB einschaltet.
