### ISSUE TITLE
[LTB]  Lerntagebuch

### ISSUE THREAD

**Issue by FKneer** [e-Learning-by-SSE/nm-self-learning#163]
Implementierung des überarbeiteten Lerntagebuch basierend auf den Konzept [25](https://github.com/e-Learning-by-SSE/nm-concept/issues/25) und dem Papierprototypen [28](https://github.com/e-Learning-by-SSE/nm-concept/issues/28):

- [x] Lerntagebuch Übersicht (Seite)
- [ ] Lerntagebuch Einträge (Seite)
   - [ ] Dialog Detailansicht
   - [ ] Dialoge Eingabe von Informationen (Ort, Ablenkungen, Bemühungen, Notizen, Lernziele)
   - [ ] Dialog Lernstrategien
- [ ]  Lernziele (Seite)

Diskussion Psychologie siehe [academic cloud 2024-05-15 Lerntagebuch.pptx](https://sync.academiccloud.de/index.php/f/521517934)

## Tagebuch Übersicht:

- Filteroptionen für die einzelnen Spalten, individuelle Übersicht für die Einträge
- Sortierung nach Spalten
- Weiterleitung zu einem Eintrag durch klick auf Zeile.

![Tagebuch_Übersicht_Eintrag](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/109528940/68baf9de-58ce-411e-ba65-0bf18ff62b80)

## Tagebuch Eintrag:

- Auf dieser Seite kann jetzt der Eintrag zu der Lernsession bearbeitet werden:
- Über das Stift-Symbol öffnen sich jetzt die Dialogfelder, in denen ausgewählt oder eingetragen werden kann.
- Und sobald es gespeichert wurde, erscheint der gewählte Eintrag.
- Und dann auf speichern geklickt wird. Hier haben wir diskutiert, ob es nicht einfacher wäre, wenn es automatisch gespeichert wird.
- Wenn ein Eintrag fertig ist, kann man über „Übersicht“ zurückgehen.
- [ ] Diskussion Menge an Dialogen zur Eingabe
   - Aktuell einzelne Dialoge für Ort, Lernziele, Strategien, Ablenkung, Bemühungen und Notizen

### Leerer Tagebucheintrag (neuer Eintrag)
![Tagebuch_Eintrag_unausgefüllt](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/109528940/37866427-5460-4875-863a-92ad505c612a)

### Ausgefüllter Eintrag
![Tagebuch_Eintrag](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/109528940/71cf705e-2e93-4522-b9be-f88aea847114)

#### Detailansicht Lernsession 
![Tagebuch_Eintrag_Detailansicht](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/109528940/ac908891-f3b5-4404-9e3f-db4ec8aaade2)
#### Lernstrategie Dialog 
![Strategien_Dialog](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/109528940/b183caeb-d3ad-48ca-9c3a-70b6f89fc94e)
#### Eingabe Dialoge
![Dialoge](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/109528940/0afc6390-0cd5-48b9-ba4e-863dec63239f)
#### Zieldialog
![Zieldialog](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/109528940/577d23f3-2bb0-40e3-abf6-9afb0b879c4b)

## Lernziele:

- Zu sehen sind alle persönlichen Lernziele incl. des Bearbeitungsstandes (hier im Prinzip, wie ein Ampelsystem, rot = noch nicht bearbeitet, gelb = zum Teil bearbeitet und grün = fertig)
- Wir benötigen für alle Ziele die Option einer Namensänderung und die Möglichkeit, die Ziele zu löschen. Abgeschlossene „grüne“ Ziele können weder editiert noch gelöscht werden. Feinziele können auch zu  Grobzielen hochgestuft werden.
- Die Feinziele können durch Pfeile (wie in dem Kurseditor in der Lernplattform) nach oben bzw. unten verschoben werden, um eine Rangreihenfolge in den Feinzielen abzubilden.

![Lernziele](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/109528940/ba64216a-4184-4af6-b754-bbe8acd22f28)

**Comment by ganskem** [comment]
Wird in kleinere Issues zerlegt:

vgl. #164 usw.

**Comment by FKneer** [comment]
Duplikate: #168 #169 #164 
closed
