### ISSUE TITLE
[LTB] Lerntagebucheintrag

### ISSUE THREAD

**Issue by ganskem** [e-Learning-by-SSE/nm-self-learning#168]
Nachfolgend wird beschrieben, wie ein Lerntagebucheintrag in der Lernplattform präsentiert wird und wie Studierende diesen bearbeiten können. Ein Eintrag ist dabei grob in die automatisch generierte Detailansicht und eine Vielzahl an durch Studierende ausfüllbare Kacheln über Einzelheiten zu den durchgeführten Lernaktivitäten in der Lernsequenz unterteilt. Weiterhin existiert eine Navigationskomponente um zwischen Tagebucheinträgen zu wechseln.

- [x] Detailansicht
- [x] Lernort
- [x] Lernstrategien
- [ ] Lernziel
- [x] Bemühungen
- [x] Ablenkungen
- [x] Notizen
- [x] Navigationskomponente

### Detailansicht
Die Detailansicht fasst automatisch erfasste Daten über eine konkrete Lernsequenz eines Studierenden zusammen.

**Vorschau**
In der Vorschau der Detailansicht wird das Datum, der bearbeitete Kurs, die Dauer der Lernsequenz sowie der Umfang der Lernsequenz gemessen an der Anzahl der bearbeiteten Lerneinheiten angezeigt. Über einen Button kann die Detailansicht geöffnet werden.

![grafik](https://github.com/user-attachments/assets/a2154140-99cd-4db4-8609-0a98271311ab)

**Geöffnetes Dialogfenster (tabellarische Übersicht)**
Nachdem die Detailansicht geöffnet wurde, wird eine tabellarische Zusammenfassung der Lernaktivitäten des Studierenden in der Lernsequenz angezeigt. Die Zusammenfassung ist dabei auf dem Aggregationslevel einzelner Lerneinheiten. Pro Zeile der Tabelle werden die Lernaktivitäten in einer Lerneinheit zusammengefasst. Dabei stehen die Spalten:

- Lerneinheit,
- Dauer,
- Aufgaben,
- Richtig,
- Falsch und 
- Hinweise

zur Verfügung. Die Tabelle muss dabei für jedes Feld aufsteigend und absteigend sortiert werden können.

![grafik](https://github.com/user-attachments/assets/fea44e7b-5c8d-4dae-b29c-c3be1ebc88e4)

**Anpassbarkeit der tabellarischen Übersicht**
Um Studierenden eine genauere Betrachtung der Lernaktivitäten zu ermöglichen müssen einzelne Spalten eingeblendet und ausgeblendet werden können. Die Spalte der Lerneinheit muss immer sichtbar sein.

### Weitere Felder
Beim Erstellen eines Tagebucheintrags sind die durch den Nutzer auszufüllenden Kacheln initial leer. Die Kachel müssen durch Anklicken bearbeitet und mit Informationen gefüllt werden können. Nicht bearbeite Kacheln sind dabei mit einer gestrichelten Linie umgeben und rot hinterlegt. Bearbeitete Kacheln wiederum sind mit einer durchgezogenen Linie umgeben und weiß gefärbt. Jede Kachel hat einen Titel, ein Stift-Icon zum Bearbeiten und ein Inhaltsfeld. Im Inhaltsfeld steht initial: „Noch kein(e) <Platzhalter> hinterlegt.“.

### Lernort
Beim Bearbeiten des Lernorts muss sich ein Dialogfenster öffnen, in dem Studierende zwischen den Lernorten Zuhause, Unterwegs und Universität auswählen können. Weiterhin muss ein offenes Eingabefeld vorhanden sein um eine Alternativauswahl zu ermöglichen.

![grafik](https://github.com/user-attachments/assets/1138efc3-d420-49d3-a44a-ea7d6c8fc04c)

**Ausgefüllte Kachel**
Nachdem der Lernort gespeichert wurde, wird der Lernort in der Kachel eingeblendet.

![grafik](https://github.com/user-attachments/assets/c13eb716-b835-436f-97e5-b13037a08c39)

### Lernstrategien
Beim Bearbeiten der Lernstrategien muss sich ein Dialogfenster öffnen, in dem alle Lerntechniken nach Lernstrategien gruppiert dargestellt werden. 

![grafik](https://github.com/user-attachments/assets/41f80796-6933-4726-9188-2a602d2a03e8)
![grafik](https://github.com/user-attachments/assets/92ad332a-4f6b-45cd-8e88-955a15b1dc6f)

**Auswahl und Bewertung vordefinierter Lerntechniken**
Beim Anklicken einer Lerntechnik muss sich ein Bewertungsfenster öffnen, in dem Studierende 1 bis 5 Sterne vergeben können. 

**Hinzufügen und Bewerten eigener Lerntechniken**
Weiterhin muss ein offenes Eingabefeld für alternativ verwendete und nicht in der Liste vorkommende Lerntechniken vorhanden sein. In diesem Fenster müssen Studierende eine Lernstrategie auswählen, den Namen der neuen Lerntechnik angeben und diese ebenfalls mit 1 bis 5 Sternen bewerten.

**Ausgefüllte Kachel**
Nachdem die Lerntechniken und deren Bewertungen gespeichert wurden, werden in der Kachel die Namen und die Bewertung der bewerteten Lerntechniken angezeigt. Dabei wird immer eine Lerntechnik und deren Bewertung einzeln angezeigt. Studierenden wird ermöglicht, z.B. durch Akkordeon, zwischen den Strategien zu wechseln.

![grafik](https://github.com/user-attachments/assets/936980c4-8f3b-4dcc-894b-cbd9c758505b)

### Lernziele
Beim Bearbeiten der Lernziele muss sich ein Dialogfenster öffnen, in dem Studierende aus den zuvor angelegten Lernzielen auswählen und diese bewerten können.

**Auswahl der Lernziele**
Es werden die im Dialog der Lernziele angelegten Grobziele mit den dazugehörigen Feinzielen angezeigt (vgl. Lernzieleditor von Fabian). Bereits abgeschlossene Grob- und Feinziele werden nicht angezeigt. Noch nicht abgeschlossene Feinziele können dann von Studierenden in ihrer Bewertung des Fortschritts verändert werden.

![grafik](https://github.com/user-attachments/assets/559a9a24-93b3-43a5-a9e2-83c9f5ebfe98)

**Ausgefüllte Kachel**
Die ausgefüllte Kachel zeigt die veränderten Bearbeitungsstatus der Feinziele.

![grafik](https://github.com/user-attachments/assets/3fb222da-e97d-4a0c-a9db-267f31756706)

* _ggf. kann hier zusätzlich ein Informationstext eingeblendet werden: "Der Bearbeitungsstatus von Lernziel A wurde von nicht bearbeitetet auf bearbeitet gesetzt". Andernfalls ist die Änderung nicht offensichtlich._

### Bemühungen
Beim Bearbeiten der Bemühungen muss sich ein Dialogfenster öffnen, in dem Studierende eine Bewertung von 1 bis 5 Sternen vergeben können.

![grafik](https://github.com/user-attachments/assets/96d5d4ad-a82b-48ea-b10e-ca9f2b5c6ee2)

**Ausgefüllte Kachel**
Nachdem die Bemühungen gespeichert wurden, wird die Ausprägung der Bemühung in der Anzahl der vergebenen Sterne in der Kachel angezeigt.

![grafik](https://github.com/user-attachments/assets/f0169fcc-c645-4e8d-a899-d86b54d9b58a)

### Ablenkungen
Beim Bearbeiten der Ablenkungen muss sich ein Dialogfenster öffnen, in dem Studierende eine Bewertung von 1 bis 5 Sternen vergeben können.

![grafik](https://github.com/user-attachments/assets/cc6dcf92-a5f7-40db-966b-1f3208eec084)

**Ausgefüllte Kachel**
Nachdem die Ablenkungen gespeichert wurden, wird die Ausprägung der Ablenkung in der Anzahl der vergebenen Sterne in der Kachel angezeigt.

![grafik](https://github.com/user-attachments/assets/03c5038c-5753-40d2-883f-c701c95e87a5)

### Notizen
Beim Bearbeiten der Ablenkungen muss sich ein Dialogfenster öffnen, in dem Studierende einen Text in einem Textfeld schreiben können.
 
![grafik](https://github.com/user-attachments/assets/0793f249-fa8b-496b-81ea-b4bb2aa2c343)

**Ausgefüllte Kachel**
Nachdem die Notizen gespeichert wurden, wird der verfasste Text in der Kachel eingeblendet.

![grafik](https://github.com/user-attachments/assets/d50829ca-b4d5-465e-a013-88037f313e78)

### Navigationskomponente
Oberhalb des Tagebucheintrags muss sich eine Navigationskomponente befinden, die es Studierenden ermöglicht, zwischen Tagebucheinträgen zu wechseln. Dazu stehen zentral Buttons zum Springen zum Vorherigen und Nächsten Tagebucheintrag. Weiterhin befindet sich zwischen diesen Buttons ein Eingabefeld mit dem direkt eine ID eines konkreten Tagebucheintrags ausgewählt werden kann. Abschließend ist ein Button vorhanden um wieder zur Übersicht des Lerntagebuchs zu gelangen.

![grafik](https://github.com/user-attachments/assets/d63bcb32-4e97-49b0-8b07-3bfc1573f17d)

**Comment by palfner-sse** [comment]
Hier werden Fotos benötigt, verwende momentan die von #163.

**Comment by ganskem** [comment]
Ergebnisse des Gesprächs zusammen mit @spark-sse und @palfner-sse über den Zeitpunkt der Erstellung und des Schließens eines Lerntagebucheintrags.

![grafik](https://github.com/user-attachments/assets/37ba0fc1-4c92-4aee-9a2e-2461b2b892b9)
![grafik](https://github.com/user-attachments/assets/ff0b2324-aca2-458d-8201-00d041d1f7ad)

**Bemerkung:** Der im ersten Bild erwähnte "threshold" von einer Minute gilt sowohl für das automatisierte Anlegen eines Lerntagebucheintrags als auch das darauffolgende automatische Eintragen bearbeiteter Lerneinheiten (d.h. eine Lerneinheit wird in einem Tagebucheintrag erst dann "bearbeitet" aufgelistet, wenn sich ein Student mindestens 1 Minute in dieser befunden hat)
