### ISSUE TITLE
[LTB] Lerntagebuchübersichtsseite

### ISSUE THREAD

**Issue by ganskem** [e-Learning-by-SSE/nm-self-learning#169]
Einstieg Lerntagebuch
-	Tabellarische Ansicht mit verschiedenen Spalten:
o	Nr: Die Nummer des Eintrags
o	Kurs: Der Kurs auf den sich ein Eintrag bezieht
o	Datum: Das Datum an dem der Eintrag erstellt wurde
o	Dauer: Die Lerndauer
o	Lernort: Der vom Studenten ausgewählte Lernort
o	Lernstrategien: Eine Zusammenfassung der angewendeten Lerntechniken
	Werden bspw. 3 Techniken der Kognition angegeben so steht: „Kognition 3“
o	Lerntechniken
-	Spalten müssen vom Nutzer ein- und ausgeblendet werden können
o	Als Default sollten nur Nr, Kurs, Datum und Dauer angezeigt werden
-	Jede Spalte kann auf- und absteigend sortiert werden
-	Weiterleitung zum Eintrag durch Klick auf Tabellenzeile

**Comment by spark-sse** [comment]
@ganskem 

wir  sollten einmal auf die aktuelle version schauen ob das so passt. ASAP; am besten ma 22.09 zwischen 10-14 Uhr (serverwartungsarbeiten)
