### ISSUE TITLE
Datenbank Migrationen einspielen

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#200]
Teilweise können die Prod-Daten schon einmal in das aktuelle Schema überführt werden. Kurz vor dem Release wird es zwar noch einmal einige merges geben, aber bestehende Daten werden dann nicht mehr angepasst. Es werden nur Informationen dazu kommen.

Das kann uns hinten raus zeit sparen

**Comment by spark-sse** [comment]
Ich denke mal der automatisierte part ist der geringere Aufwand. Ich weiß gerade nicht wie viel wir manuell machen müssen. Wir sollten uns aber darauf vorbereiten, dass migrationen auch das schreiben von manuellen skripten beinhaltet. Auch wenn wir das noch nicht diese migration machen, wird das möglicherweise in kommenden versionen der fall sein. 

Ich denke ein MIgrationsschritt beinhaltet eine SQL-Skript (vermutlich ausgeführt via npm+prisma?) und ein ts/js node-skript, für die JSON values in der datenbank. Das sollte auch alles relativ easy und typsicher gehen. 

2. ich weiß gerade nicht um welche Wünsche es sich handelt. Bis auf die Shuffle Funktion wird aber keines der erwähnte Features bis zum Oktober fertig sein
3. Ein gängiges Vorgehen wäre das entry-skript so zu bauen, dass erkennt ob migrationen eingespielt werden müssen. Dann kann von dort auch prisma + das node skript ausgeführt werden. Cool wäre auch, wenn man in der docker compose einfach das entry/CMD überschreiben kann und zB selber npm befehle ausführen kann. Dann kann man für die ganzen edge cases, einfach doku schreiben, aber braucht keine skripte schreiben (zB dass die DB zurückgesetzt werden soll, oder Datenverlust aktzeptiert werden kann etc). Ich skizziere mal einen Vorschlag der auf zusätzliche env variablen verzichtet, aber genauso komfortabel ist:
      - entry.sh[1]: Prüft ob Migrationen notwendig sind bzw führt sie indempotent aus. zB `npm run migrate`. Anschließend ist es ein `npm run` wrapper
      - `start`via cmd
      - eine env für seed finde ich zwar nicht schlecht, aber wenn man den obigen ansatz wählt, kann man auch einfach das cmd überschreiben zB `seed`. Beispiel ist unten
4. Darum kümmere ich mich. Setze dann einfach ein Klon der Prod-Instanz auf. 


[1] entry.sh

```
#!/bin/bash
set -e

echo "Prüfe auf Migrationen..."
# .... check if necessary
npm run migrate

echo "Starte die Anwendung..."
exec "npm run $@"

```

zugehörige Dockerfile
```
FROM node

# ...
# ... 

ENTRYPOINT ["./entrypoint.sh"]
CMD ["start"]

```

Bsp für eine Docker compose fürs seeding (angenommen die package.json kennt ein "seed" target: 
```
services:
  myapp:
    command: ["seed"] // runs "npm run seed" through entry.sh
```

Statt das `npm run start` aufgerufen wird, wird der container via oneshot mit "npm run seed" aufgerufen. Anschießend kann die anwendung wieder ohne `command aufgerufen werden.

**Comment by Elscha** [comment]
Von der automatischen Identifikation ob eine Migration eingespielt werden muss, würde ich gerne weg, da mir gerade kein guter Ansatz einfällt dieses festzustellen.
* Derzeit legen wir eine Datei an und wenn diese existiert können wir davon ausgehen, dass die DB initialisiert wurde. In Zukunft kann man immer alle Migrationen einspielen. Ist an sich sehr Hackie.
* Alternativ: Wir lassen immer alle Migrationen durchlaufen. Da Prisma notiert welche bereits eingespielt wurden, ist das eigentlich so gut möglich. Problem: Wenn das System aufgesetzt wird. Dann müssen ggf. bereits einige Migrationen als bereits eingespielt markiert werden, ansonsten werden viele Fehler in die Prisma-interne DB eingetragen, die manuell gelöst werden müssen.

In Search haben wir dazu eine System-Variable eingeführt (der Ansatz des Start-Commands gefällt mir aber auch sehr gut):
* **INIT**: Setzt DB auf (`npx prisma db push`), führt ggf. Seed aus und markiert alle vorhandenen Migrations als bereits eingespielt (`npx prisma migrate --applied ...`). Das markieren der Migrationen ist wichtig für das Aufsetzen weiterer Instanzen zu einem späteren Zeitpunkt (anderer Version, die nicht alle Migrationen benötigt).
* **Migrate**: Führt alle offenen Migrationen durch. Pro Migration muss man dann ggf. auch entsprechende Daten einspielen (in SEARCH nicht relevant, hier u.U. schon).
* **DEMO**: Wie INIT + Demo-Seed um die Anwendung lokal zu testen.
* **RESET**: Wie INIT, setzt aber die Daten komplett zurück. Auch wieder für die Entwickler gedacht und sollte im Produktiv-System auf keinen Fall gemacht werden.

Wichtig: Ich denke, dass wir Initialisierungsdaten pro Migration vorhalten werden müssen, um in Zukunft auch bei einem Aufsetzen einer neuen Instanz / Update einer älteren Instanz keine Probleme zu bekommen.

Ich werde mir das mal mit dem Target anschauen.

**Comment by Elscha** [comment]
Basierend auf https://medium.com/@BioCatchTechBlog/passing-arguments-to-a-docker-container-299d042e5ce würde ich es wie im angehängten [Prototyp](https://github.com/user-attachments/files/17093140/Prototype.zip) umsetzen.

**Comment by Elscha** [comment]
Ich habe mit 253078e5480573c23e662399b32bb4062cd3f214 von [chore/migration-script](/e-Learning-by-SSE/nm-self-learning/tree/chore/migration-script) die folgenden Tests lokal durchgeführt:
- Aufsetzen des Systems mit einer frischen DB: ✓
- Migration mittels eines Dumbs vom aktuellen System und vorheriger lokaler Verwendung des aktuellen Releases: ✓

Für beide Tests konnte der Default Start-Command verwendet werden.

Ich habe zudem einmal das Ausführen eines Oneshot-Befehls getestet, um eine Migration als bereits eingespielt zu markieren (sollte nicht notwendig sein, demonstriert aber die Fähigkeit andere Targets als Start zu definieren). Da für das Einspielen der Migrationen die Option `--applied` notwendig ist, muss man hier noch eine [Docker-spezifische Eigenart](https://github.com/moby/moby/issues/21369#issuecomment-199389076) berücksichtigen und den Befehl mit zwei vorangestellten `--` ausführen, beispielsweise in der `compose.yml` wie folgt:
```command: ["-- prisma migrate resolve --applied 0_init"]``` 
Auch dieses ist möglich: ✓

**Comment by spark-sse** [comment]
Klasse. 
Öffnest du noch eine PR ?
