### ISSUE TITLE
Refactor PageViewer Sidebar

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#208]
Sidebar beim der seitenansicht eines LTB ist aktuell recht ähnlich im vergleich zu existierenden komponenten (lesson playlists). 

Gggf. refactor?

**Comment by palfner-sse** [comment]
Ich schaue mir das mal an. Wollte das eh benutzen, aber war wegen der Zeit knapp, da habe ich das fix selbst gebaut.
