### ISSUE TITLE
Fix Jest Test Setup

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#216]
Aktuell blockiert das die komplette Test-Suite des Masters.

Ein Problem ist das test-setup. ts-jest hat kein out-of-the-box stable ESM support. Allerdings haben wir spätestens mit superjson native ESM module die probleme beim test-setup verursachen.

- [x] Fixed durch migration auf SWC/jest

Ansonsten müssen die folgenden Test fälle überprüft und ggf. behoben werden:

- [ ] com.docker.devenvironments.code (watch)
  - [x] apps
    - [x] site
  - [ ] libs
    - [x] data-access
    - [x] feature
      - [x] admin
      - [x] completion
      - [x] diary
      - [x] enrollment
      - [x] question-types
      - [x] teaching
    - [x] ui
    - [ ] util
      - [x] common
      - [ ] http
      - [x] lia-exporter
      - [x] markdown
      - [ ] testing
      - [x] types

**Comment by Elscha** [comment]
Was ist genau zu prüfen, habe die folgenden Testfälle manuell erfolgreich im DevEnv ausgeführt:
* libs
  - feature
    * completion (3/3)
      - course-completion.spec
      - lesson-completion.spec
      - mark-as-completed.spec
   * enrollment (1/1)
     - envorllments-db.spec -> Benötigt angepasstes Setup

**Comment by spark-sse** [comment]
tests sollten lokal und in der pipeline erfolgreich abschließen (eben auch mehrfach ausführung)
