### ISSUE TITLE
if the window is too small, the buttons "admin area" and "subject areas" are not displayed in the menu and cannot be found anywhere else either 

### ISSUE THREAD

**Issue by WenzelSSE** [e-Learning-by-SSE/nm-self-learning#24]
<img width="1867" alt="Screenshot 2023-01-09 at 12 51 41" src="https://user-images.githubusercontent.com/111048980/211301905-200250be-0e78-4b10-970b-5221d573cc54.png">
<img width="1433" alt="Screenshot 2023-01-09 at 12 51 31" src="https://user-images.githubusercontent.com/111048980/211301928-27d869ba-d1a4-4ee8-9139-d8210fe1da76.png">

**Comment by mspark** [comment]
Da wir hierfür ein Menü brauchen, folgende Vorschläge:

- Adminbereich kommt nach Rechts zum Stern (ggf. auch ins "Profil-Dropdown")
- Die anderen Navigationslinks können ggf. als Burger-Menü gemacht werden

**Comment by Elscha** [comment]
Ursprüngliche war ein Hamburger-Menü oben links vorgesehen, was bishalg noch nicht implementiert wurde. Es wäre schön, wenn das nachgeholt werden könnte. Hier die Vorlage (mit ausgeklappten Menü auf der linken Seite):
![Wireframe](https://user-images.githubusercontent.com/6489033/218098092-4dee16a0-b9af-4d70-b990-edf5506386f1.png)

**Comment by Arne1303** [comment]
@Elscha Können wir machen! Das Logout würde ich aber mit auf die Rechte Seite nehmen, dafür aber die "Übersicht" mit nach links in das neue Hamburger-Menü und in `Startseite`(?) umbenennen.

Ich könnte mir zusätzlich zu den Kursen die einzelnen Fachbereiche vorstellen (Maximal 4 Stück, erstmal die ersten 4 die hinzugefügt wurden später dann vll die die relevant sind für den Nutzer)

Wie ist das mit `Planer` und `Lerntagebuch` soll ich das erstmal rauslassen bis da klar ist wie das aussehen soll? Wohin soll Suche führen? Für Admins haben wir die Suche in /admin/lessons für Nutzer gibt es sowas aber glaub ich noch nicht, also auch erstmal weglassen? Sonst können wir die Admin suche auch als page für jeden freigeben und ein wenig erweitern das die Suchergebnisse mehr Informationen enthalten, wüsste nicht warum die nicht alles einfach durchsuchen sollen dürften.

Das Menü mach ich auch immer als overlay drüber legen, auch auf Desktop-Geräten. Gerade die Lernseiten währen mir sonst einfach schon zu voll als das man da noch ein festes Menü links haben könnten.

**Comment by mspark** [comment]
mit Übersicht ist der Link gemeint, der momentan mehr oder weniger als Platzhalter auf der Plattform ist (nicht im Draft). 

@Arne1303 wie besprochen:
- Übersicht kann in Startseite umbenannt werden
- Eigentlich soll links in der leiste angezeigt werden, an welchen kursen man aktuell arbeitet. Um hinsichtlich der UI schon ein paar Schritte weiter zum Ziel zu kommen, kann man wie von dir vorgeschlagen, die drei "Fachgebiete" (wie sie jetzt auf der Plattform heißen) dort ins Menü aufnehmen wo später die Kurse sein sollen.

**Comment by spark-sse** [comment]
Nicht ganz; die leiste ist nur zu sehen, wenn ein nutzer auch angemeldet ist. 

Als Anmerkung für später: Zukünftig ist geplant dass nicht angemeldete nutzer auch nicht auf den learning-content zugreifen können. Dafür müssten dann aber auch noch mehr sachen angepasst werden.
