### ISSUE TITLE
leaving page wenn User use external Links -> better solution : new window 

### ISSUE THREAD

**Issue by WenzelSSE** [e-Learning-by-SSE/nm-self-learning#25]
<img width="1863" alt="Screenshot 2023-01-09 at 13 00 59" src="https://user-images.githubusercontent.com/111048980/211303564-965603f6-d47e-4ae0-aeea-e3fa3e771a54.png">

**Comment by Elscha** [comment]
This happens usually in user-created contented, which is provided as Markdown input. There are two possible solutions:

1. Users must manually specify a `target` attribute for links. I expect this not as practicable.
2. We modify the default behavior of markdown rendered output.

For the second option I found this guide to change the default behaviour of links in MD-documents, rendered via react:

- [Answer on Stackoverflow](https://stackoverflow.com/a/69120400)
- [Example](https://codesandbox.io/s/snowy-field-r8d3c?file=/src/App.js:241-257)

After a brief look into the code, I discovered only one component, that is responsible for rendering markdown: [libs/ui/forms/src/lib/markdown-editor.tsx)](https://github.com/e-Learning-by-SSE/nm-self-learning/blob/master/libs/ui/forms/src/lib/markdown-editor.tsx). This should be the starting point for any general modifications of user input
