### ISSUE TITLE
Admin lockout without demo accounts

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#28]
When the app is deployt without the demo option, no demo logins are possible. But there is no possability to change the role of OIDC users. 

This results in an complete administrative lockout. 

Expected behaviour: There should be a mechanism to set admins. 
Like:
- OIDC Token contain an admin role which are taken into account by this app
- The first OIDC successful OIDC login is automatically an admin user

**Comment by mspark** [comment]
Second option is assigned to @Arne1303

**Comment by Arne1303** [comment]
Talked with @mspark about this, for now we will implement a fix which makes the first user of the instance an admin user. Later down the line we will change this so that the admin role is given through OIDC.
