### ISSUE TITLE
OER / License-Model

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-self-learning#30]
Sharing of Nano-Modules is one of the main ideas of the project. However, we did not consider the broad range of possibilities, especially related to Open Educational Resources (OER):
- Is it allowed to use content (e.g., videos) and questionnaires outside of the platform
- Are we allowed to copy, edit, and extend existing Nano-Modules?
- Do we need to name the original author(s) of a Nano-Module?

I suggest that users should be able to specify a CC-license for a new Nano-Module. Whenever a Nano-Module is referenced/copied, the platform should only support valid operations (export, edit, re-use of Nano-Modules).

This [link](https://wb-web.de/material/medien/die-cc-lizenzen-im-uberblick-welche-lizenz-fur-welche-zwecke-1.html) (German) provides an overview about the CC license derivations that may be used for OER. Starting with CC-BY-NC-SA (and above) is considered as OER.

**Comment by spark-sse** [comment]
Added first logos for OER-compatible licenses (CC-based licenses)

**Comment by spark-sse** [comment]
Closed with #40
