### ISSUE TITLE
Moodle <-> Self-Learn Integration

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-self-learning#32]
Durch Button klickt sollte man aus dem Moodle angemeldet in die Self-Learn Plattform gelangen (analog zum BBB-Raum öffnen Feature).
**Optional:** Dozent kann Ziel-Kurs spezifizieren, in dem man beim Klick landet.

**Vorgehen:**
- [ ] Moodle sendet durch Moodle signierten Token an KeyCloak mit LDAP-ID des Benutzers (Fabian)
- [ ] KeyCloak stellt Token für Self-Lern aus, für die angegebene LDAP-ID (Marcel)
- [ ] Moodle sendet mit gültigen KeyCloak (Bearer Token) Anfrage an Self-Learn (Fabian)

**Comment by spark-sse** [comment]
Issue macht an dieser stelle kein sinn da ausschließlich moodle und keycloak involviert sind und keine code änderungen an der selflearn plattform notwendig werden.
