### ISSUE TITLE
Courses added directly to a subject

### ISSUE THREAD

**Issue by FKneer** [e-Learning-by-SSE/nm-self-learning#33]
Currently a new course requires a subjectid and a specializationid. This means that a course can only be added to a specialization.  

current structure Psychologie:
subject: "Psychologie" 
specialization: "Aufmerksamkeit"
course: "Aufmerksamkeit"

needed structure:
subject: "Psychologie"
course: "Aufmerksamkeit"

**Comment by spark-sse** [comment]
**Update**:

See https://github.com/e-Learning-by-SSE/nm-concept/issues/5

> Es ist nicht sinnvoll den aktuellen Kurseditor anzupassen. Die alte Struktur beinhaltet Kapitel, und eine 1:n Beziehung von Lerneinheiten zu Kursen. So etwas würde es zukünftig eventuell nicht mehr geben, da die Nano-Module eines Kurs vermutlich (?) nur noch über die Lernziele bestimmt wird (also dem daraus generiertem Pfad).

There will be a new structure, but it is currently unclear what it will look like. We are taking this issue into account in the concept phase, but overall we will not be making any further adjustments to the current structure. 

For more clearance, can you elaborate why the second structure is needed?
