### ISSUE TITLE
[bug] Video and Text not loading correctly in lesson

### ISSUE THREAD

**Issue by lukas-png** [e-Learning-by-SSE/nm-self-learning#44]
1. Open for example the Seeded Course Objectorientierung
2. Goto einleitung und motivation (the video is there)
3. Goto installation des jdks (Error: missing url) -> instead the text should be displayed
4. refresh site
5. Goto einleitung und motivation again (video dont load) ->it should be there

**Comment by lukas-png** [comment]
Der Fehler ist auch bei Selbst angelegten Lerneinheiten vorhanden

**Comment by spark-sse** [comment]
https://github.com/user-attachments/assets/24d02c0a-a63d-4df2-a20e-35ddf134bd25

wirkt wie das gleiche problem
