### ISSUE TITLE
Suchfunktion in der oberen Leiste

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#53]
Es sollte eine (gemeinsame) Suchfunktion auf der Plattform geben, die einen ermöglich Kurse und Lerneinheiten zu finden. 

Wird z.B. "Analysis" gesucht, sollte der oberste Treffer der Analysis Kurs sein (da exakter Treffer). Alle weiteren Ergebnisse wären dann die Lerneinheiten aus dem Kurs. 

Die Suchleiste sollte neben den Namen in der oberen Navigationsleiste [Bild1]

[Bild1]
![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/113825305/60a29997-7278-46ab-8e18-056b92f0871e)

**Comment by Arne1303** [comment]
Heutiges Gespräch mit @spark-sse, es gibt es Probleme beim Durchsuchen der Lerneinheiten. Aktuell ist es nicht möglich von einer Lehrneinheit den Kurs zu bekommen, weswegen die Suche nicht die URL zum Anzeigen bauen kann. Es wurde entschieden, dass wir stattdessen die URL zum Bearbeiten nehmen werden, da diese den Kurs nicht benötigt. Die Suche nach Lerneinheiten wird später nochmal nachgearbeitet, sobald die Kursstruktur entsprechend angepasst wurde, das passiert in https://github.com/e-Learning-by-SSE/nm-concept/issues/5 und https://github.com/e-Learning-by-SSE/nm-concept/issues/2

**Comment by spark-sse** [comment]
Verbesserungen sing geplant in #128
