### ISSUE TITLE
Buttons zum Hinzufügen von Elementen zu Ordnen-Tests verschwinden bei kleineren Viewports

### ISSUE THREAD

**Issue by ganskem** [e-Learning-by-SSE/nm-self-learning#55]
Beim Herunterskalieren der Webseite, z.B. wenn man zwei Fenster nebeneinander hat, verschwinden die Buttons zum Hinzufügen von Elementen zu den einzelnen Kategorien im Ordnen-Test.

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/1a3abe15-e6fc-4fdf-a5ce-1d3fad7bb79e)

**Comment by spark-sse** [comment]
will be worked on in #87

**Comment by palfner-sse** [comment]
Fix applied via Issue #87 and Pull request #114
