### ISSUE TITLE
Anderer Font im Lerntypen-Dropdown

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#59]
![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/113825305/c91ba3aa-eda8-4380-825a-fa4e989884fd)

**Comment by spark-sse** [comment]
Issue betrifft alle derartige Auswahlfelder in der Seitenleiste (zB Lizensauswahl). Der Font verändert sich in unterschiedlichen Browsern. Evtl ist hier ein Fallback auf den default Font der Browser?

**Comment by Arne1303** [comment]
Ja aktuell ist das immer der Default vom Browser, ich bin mir auch noch nicht sicher wie wir das lösen. Nach Spec https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#styling_with_css kann man das `option` Element kaum mit css anpassen. Die einzige Lösung die mir so weit eingefallen ist das man eine 3rd Party library für die Dropdown verwendet (z.B. Select2) aber das will ich möglichst vermeiden.

**Comment by spark-sse** [comment]
Das Problem existiert auch in jedem anderen Select-Field in der Plattofrm. 

Für firefox hab ich sowas hier gefunden:

```html
<select>
<optgroup style="font-family:arial">
    <option>Arial</option>
</optgroup>
<optgroup style="font-family:verdana">
    <option>veranda</option>
</optgroup>
```

Aufgrund der Art des Problems wird dieser Fehler allerdings nicht behoben.
