### ISSUE TITLE
Dialog zum editieren von Autoren skaliert falsch

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#60]
Der Dialog zum anpassen von Autoren (Adminansicht) skaliert falsch je nach Seitenverhältnissen. z.B. verschwinden Teile aus dem Dialog, ohne das Scrollen erlaubt ist: 

Siehe Bild: Je nach Seitenverhältniss, passt isch der Dialog an. Es gibt keine Möglichkeit um an den Inhalt (z.B. zu dem Speichern-Button) nach unten zu gelangen. 

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/113825305/69476f74-9330-4243-b52f-065ec4a020e4)

**Comment by lukas-png** [comment]
@spark-sse ist fertig

**Comment by spark-sse** [comment]
Bitte PR erstellen.
