### ISSUE TITLE
Sperren von Inhalten für nicht angemeldete Nutzer

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#62]
Die Kursinhalte sollten für nicht angemeldete Nutzer ausgeblendet sein.

Eine elegante Lösung wäre, zwar die Kurse die auf der Plattform sind anzuzeigen, aber nicht die Nano-Module / Inhalte der Nano-Module.

Zu Klären @ganskem : 
Was wird nicht angemeldeten Nutzern angezeigt:
- Fachgebiete
- Kurse
- Nano-Module (die Aufteilung ohne die konkreten Inhalte)

**Comment by ganskem** [comment]
Nicht angemeldete Nutzer sollten in der Lage sein die Struktur der entwickelten Selbstlernplattform zu verstehen, insbesondere die Gliederung des Inhalts. Ein Bearbeiten der Nanomodule soll jedoch unterbunden werden. Die Funktionen der Plattform (Lernpfad, Lerntagebuch, etc.) sollen nur für angemeldete Nutzer erreichbar sein. 

Nicht angemeldete Nutzer sollten folgende Seiten sehen können:

- Übersicht der Fachgebiete (https://www.uni-hildesheim.de/selflearn/subjects)
- Übersicht der Spezialisierungen in einem Fachgebiet (https://www.uni-hildesheim.de/selflearn/subjects/psychologie)
- Übersicht der Kurse in einer Spezialisierung (https://www.uni-hildesheim.de/selflearn/subjects/psychologie/wahrnehmung)
- Übersicht der Lerneinheiten in einem Kurs (https://www.uni-hildesheim.de/selflearn/courses/das-wahrnehmungssystem-zum-fuehlen)

Nicht angemeldete Nutzer sollten folgende Inhate **nicht** sehen können:

- Der Button "Zum Lernplan hinzufügen" auf der Seite zur Übersicht der Lerneinheiten in einem Kurs sollte zum Login weiterleiten.
- Einzelne Nanomodule (https://www.uni-hildesheim.de/selflearn/courses/das-wahrnehmungssystem-zum-fuehlen/aufbau-und-funktion-haut)
