### ISSUE TITLE
Navigation zwischen Lerninhalt und Lernkontrolle verbessern

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#76]
### Aktuelles Verhalten:

Es gibt keine direkte Möglichkeit, von der Lernkontrolle zum Lerninhalt zurückzukehren. Der Fortschritt in der Lernkontrolle geht verloren, wenn man die Seite verlässt.
Gewünschtes Verhalten:

 Der Button in der linken Navigationsleiste sollte dynamisch umbenannt werden:
 - Auf der Seite des Lerninhalts: "Zur Lernkontrolle"
 -  Auf der Seite der Lernkontrolle: "Zum Lerninhalt"
 - Der Fortschritt in der Lernkontrolle sollte beim Wechseln der Seiten erhalten bleiben.

![grafik](https://github.com/e-Learning-by-SSE/nm-concept/assets/118170487/fb3a2079-edaa-489e-8fab-fd856c7abab5)
_Button in der Navigationsleiste_

![grafik](https://github.com/e-Learning-by-SSE/nm-concept/assets/118170487/a0d3c72b-5c0a-4227-9709-f581be92e647)
_Button unterhalb des Videos_

### Technische Anforderungen:

- State-Management implementieren, um den Fortschritt in der Lernkontrolle zu speichern.
- Das Label und die Aktion des Navigationsbuttons dynamisch basierend auf der aktuellen Ansicht aktualisieren.

### Akzeptanzkriterien:

- Das Button-Label ändert sich dynamisch je nach aktueller Ansicht.
- Kein Verlust des Fortschritts beim Navigieren zwischen den beiden Ansichten

**Comment by lukas-png** [comment]
### Bericht über die Entscheidung zur Speicherung der Daten im Rahmen des Gesprächs mit @spark-sse  und @palfner-sse
Da die ursprüngliche Lösung, die Daten im Localstorage zu speichern, aufgrund des Serverside rendering nicht umsetzbar war, haben wir uns nach einer Alternativlösung umgesehen. Wir haben zwischen der Speicherung in einem Cookie und der Speicherung in einer Session verglichen und uns für die Session entschieden. Unsere Gründe dafür sind folgende: 

1. Cookies werden bei jeder Anfrage an den Server mitgeschickt, was zu einem unnötigen Datentransfer bei allen anderen Funktionen führt. 
2.  Cookies sind für die Nutzer leicht zugänglich und manipulierbar, was ein Sicherheitsrisiko darstellt, falls in der Zukunft Studenten einen Abschluss der Fragen als Studienleistung oder ähnliches benötigen.

Session hingegen sind nur temporär und für die Nutzer nicht ohne weiteres einsehbar.

**Comment by lukas-png** [comment]
### Bericht über Änderung an Datenspeicherung @spark-sse @palfner-sse 

Statt es jetzt auf Server side zu Speichern wird es jetzt als React State bis zum neuladen der Webseite clientseitig gespeichert.

Begründet durch wird dies, durch Informationsgewinn durch eine weitere Recherche.  Es haben sich folgende neue Informationen ergeben:

1. Eine Speicherung im State ist trotz der schwierigen Architektur an dieser Stelle doch möglich.
2. Eine Struktur zum ändern von Sessions ist noch nicht vorhanden und müsste erst erstellt werden ( Ist einer eher unschöne Lösung mit einem Api Call vom Client zum server

**Comment by Klausmp** [comment]
Feature ist erflogreich Implementiert. Die Speicherung des momentanen Standes funktioniert bis die Seite neugeladen wird.
