### ISSUE TITLE
Learning View: Support alternative didactic model "Selbstreguliertes Lernen"

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-self-learning#8]
Support an alternative didactic model **"Selbstreguliertes Lernen"**. For this, authors have to provide additional information:

- An open question
- A Multiple Choice question

The system should provide the following process at the learning view:

1. Provide the open question. The answer won't be evaluated. For instance: *Was wissen Sie bereits über Schleifen?*
2. After answering the previous questions, the system should deliver the learning content.
3. For each answer of the multiple choice question, the system should deliver an open question at which the students should argue, why this is (in)correct. This won't be evaluated neither. For instance: *if ist eine Schleife*
4. Deliver the multiple choice question. For instance: *Welche Aussagen sind korrekt?*
   - *do-while ist eine Schleife*
   - _while ist keine Schleife_
   - _if ist eine Schleife_
   - _for each ist eine Schleife_

**Comment by Arne1303** [comment]
Hier ist ein erstes "MockUp" für das Modal der Aktivierungsfrage:
![grafik](https://user-images.githubusercontent.com/25080047/236411004-2d793a8d-6779-47f4-86bb-d67dac0a95e3.png)

Die AKtivierungsfrage kann im Editor für Lerneinheit hinzugefügt werden:
![grafik](https://user-images.githubusercontent.com/25080047/236411074-4421974e-9201-4c3a-a58e-459422f390e0.png)
