### ISSUE TITLE
Clicking on "Im separaten Editor öffnen" forwards to 404 page

### ISSUE THREAD

**Issue by ganskem** [e-Learning-by-SSE/nm-self-learning#83]
When you click on a learning unit inside the course editor, a pop-up editor for learning units will open. In the editor you are given the option to open the unit in the separate editor. Clicking the link forwards to the 404 page of the university.

Steps to reproduce:

1. Select a learning unit in the course editor
2. Click on "Im separaten Editor öffnen" Button

![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/2c895af7-c179-4612-acf0-5683393942d9)
![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/4c685a47-1182-495f-83d1-1a0e7ee16f9d)

**Comment by ganskem** [comment]
Solution Suggestion

In the file libs > feature > teaching > src > lib > course > course-content-editor > dialogs > edit-lesson-dialog.tsx the href needs to be updated to href={`selflearn/teaching/lessons/edit/${initialLesson?.lessonId}`}

**Comment by spark-sse** [comment]
As a note; this is somewhat related to #87

**Comment by palfner-sse** [comment]
Fix applied via #87
