### ISSUE TITLE
Einheitlicher LU-Editor in der Plattform

### ISSUE THREAD

**Issue by spark-sse** [e-Learning-by-SSE/nm-self-learning#87]
Wir haben aktuell mehrere verschiedene Skill-Editoren am Start, die sich in Verhalten, Funktionen und aussehen unterscheiden. Der eine ist unser Haupt-Editor, den ihr über Dashboard > Neue Lerneinheiten findet. Dieser wurde stetig weiterentwickelt. Ein Beispiel für einen anderen Editor ist der Dialog-Editor im Kursmenü. Wenn ihr über die Kursansicht neue Lerneinheiten taucht dieser als Dialog auf. Wir wollen das Ganze jetzt einheitlich gestalten. Hierfür sind folgende Schritte geplant:

- [x] **Identifizierung der Vorkommnisse:** Hierbei werden alle Instanzen und Anwendungen der verschiedenen Editoren im System erfasst. Dies umfasst, wo und wie sie eingesetzt werden.

- [x] **Besprechung der Lösungsmöglichkeiten:** In diesem Schritt wird ein Team-Meeting durchgeführt, um verschiedene Ansätze zur Vereinheitlichung zu diskutieren. Dies könnte die Auswahl eines Editors für alle Instanzen oder die Entwicklung eines neuen, konsolidierten Editors umfassen.
   - [ ] Entscheidung mit Architectural Decision Record dokumentieren

- [x] **Aufwandsschätzung:** Basierend auf den besprochenen Lösungen wird der Aufwand für die Implementierung geschätzt. Dies beinhaltet Zeit, Ressourcen und mögliche Risiken.

- [ ] #127

**Comment by lukas-png** [comment]
@spark-sse kurze nachfrage: Meinst du Lesson Editoren ?

**Comment by spark-sse** [comment]
Im Prinzip ja. Es ist aber möglich dass er je nach Anwendung im Code andere bennenungen hat. 

Zur Referenz: https://staging.sse.uni-hildesheim.de/selflearn/teaching/lessons/create vs https://staging.sse.uni-hildesheim.de/selflearn/teaching/courses/edit/q821xj7v (dort Lerneinheiten erstellen)

**Comment by lukas-png** [comment]
### Identifizierung der Vorkommnisse

#### Doppelter Lesson Editor

1.  Adminbereich -> Kurse verwalten -> Editieren / Kurs hinzufügen (Dialog Lesson Editor mit fehlenden features)
2.  Kurse hinzufügen -> Auf Kurs klicken (Full Scale Lesson Editor mit den neuen Features)

**Comment by spark-sse** [comment]
## Besprechung möglicher Lösungen

Momentan erfüllen die beiden Editoren unterschiedliche Zwecke. Der Dialog-Editor wird von Nutzern typischerweise positiver aufgenommen. Möglicherweise da simpler strukturiert, weniger überladen und typische Elemente zu finden sind (Speichern unten rechts etc.) 

Der Fullscreen-Editor wurde scheinbar eingeführt um eine Steuerung einfach (aber nicht intuitiv) zu machen. Alle Elemente sind immer auf einer Seite verfügbar ohne dass zwischen Seiten oder Tabs gewechselt werden muss. 

Ziel: Wir sollten bei Lösungen den technischen Wartungsaufwand reduzieren damit die Funktionen nicht erneut divergieren und wenn möglich gleichzeitig die Nutzererfahrung verbessern. 

Mögliche Lösung: Fokus auf den Dialog-Editor. 1. Funktionsumfang aufzurüsten. 2. Verwendung des Dialog-Editors im Adminbereich (löschen des ehemaligen Fullscreen-Editors). Technisch werden hier vermutlich ebenfalls zwei unterschiedliche React-Komponenten verwendent die allerdings die gleichen sub-komponenten beinhalten um die wartbarkeit zu vereinfachen. 3. Maximize Button in der Dialog-Ansicht (im Kursbereich) der dann auf den Editor aus dem Adminbereich umschaltet (der dann nicht im einer Dialog- sonder einer Fullscreen-Ansicht zu sehen ist).

**Comment by spark-sse** [comment]
[process update]Oben besprochene mögliche Lösung wird angegangen

**Comment by palfner-sse** [comment]
Entscheidung bezüglich der Verlinkung der Abbrechen- und Speichern-Buttons im Fullscreen-Editor

Da sowohl der Fullscreen- als auch der Dialog-Skill-Editor über Abbrechen- und Speichern-Buttons verfügen, ist eine Klärung notwendig, wohin diese Buttons im Kontext des Fullscreen-Editors führen sollen. Im Dialog-Editor führen diese Buttons zum Schließen des Dialogs. Als vorläufige Lösung werden die Buttons im Fullscreen-Editor auf "/overview" verlinken.
@spark-sse

**Comment by spark-sse** [comment]
gespräch mit @ganskem
aus gegebenen anlass werden noch designänderungen nachgereicht die beim refactoring der editoren noch berücksichtigt werden sollen

**Comment by ganskem** [comment]
Zusammenfassung des heutigen Gesprächs mit @spark-sse und @palfner-sse 

### Änderungen am Layout

Im aktualisierten LU-Editor sollen die Metadaten der Lerneinheit auf der linken Seite sein. Rechts kann über Tabs zwischen der Bearbeitung des Lerninhalts und der Lernkontrolle gewechselt werden. Änderungen innerhalb der Lerneinheit können über den Speichern-Button gespeichert werden. Diese befindet sich neben dem Abbrechen-Button nun unten rechts und ist in ihrer Position fixiert.

![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/169badbc-fe1b-4bcf-9d0b-ccc9163a600e)

-----

### **Anpassungen der Metadaten**

Die Metadaten umfassen:

- Titel
- Slug
- Untertitel
- Beschreibung
- Autoren
- Lernziele
- Lizenz
- ein neues Auswahlfeld um die Aktivierungsfrage und sequenzielles Prüfen zu aktivieren (derzeit: Lernmodell "selbstreguliertes Lernen")

![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/26d1ee7e-472f-4ae3-947d-d222fd2d36c3)
![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/0c4708d4-65b5-45c0-a73f-ae82385d2347)

Entfernt werden:

- Thumbnail (wird nicht für Lerneinheiten benötigt)
- Auswahl des Lernmodells (ersetzt durch Auswahlfeld)

-----

### Darstellung der Buttons zum Hinzufügen von Elementen

Die Buttons zum Hinzufügen von Elementen (z.B. Autoren) sollen nun rechts neben dem Titel positioniert werden. 

![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/90805a55-73d0-4af0-b98c-f08b8e891b2c)
![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/c691f6e3-40e2-4401-bb25-e2ece7c0517b)

Um weiteren Platz einzusparen sollen die Buttons zum Hinzufügen der unterschiedlichen Aufgabentypen in ein Button-Dropdown kombiniert werden:

![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/4a6f5b43-b1da-472f-8ad0-1236a16c99e7)
![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/566c5330-e137-4175-8b0b-c7cff1bdf7d5)
![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/2eb77be7-497a-45da-8e22-5be0be5ca614)

-----

### Umbenennung von Fragen zu Aufgaben

Hinzugefügte Aufgaben sollen zudem nun korrekt als Aufgabe in den Tabs angezeigt werden. Derzeit werden die Aufgaben als Frage 1, Frage 2, ... dargestellt.

![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/55dec1e7-f490-484a-ac28-af2547b331f6)
![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/b5d66190-d071-46ef-9790-28e9fef27f74)

-----

### Änderung an den Markdown-Feldern

Der Text "Markdown" über dem Eingabefeld soll entfernt werden.

![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/51e29a62-9923-4fc7-a20e-3636918cc4ee)

-----

### Vereinheitlichen der Entfernen-Symbolik im LU-Editor

Zukünftig soll auch für Hinweise, Antworten, akzeptierte Antworten (Exakte Antwort) das Kreuz-Symbol "X" verwendet werden. In der aktuellen Version werden diese Elemente über "Entfernen" entfernt.

![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/30b947bc-115e-4635-9a4e-9d2a021becb4)
![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/a0f51eda-fb06-4593-82f0-3a7834b32b25)

-----

### Ergänzen der fehlenden Überschrift der Kategorien (Ordnen)

Beim Anlegen einer Ordnen-Aufgabe fehlt derzeit die Überschrift. Es wird nur der Button zum Hinzufügen von Elementen angezeigt.

![image](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/118170487/53c097ef-917f-40a2-9db4-1a3f9bad9c8d)

**Comment by ganskem** [comment]
Nach Rücksprache mit @palfner-sse wurde entschieden den Bereich der Metadaten einklappbar zu gestalten.

**Comment by palfner-sse** [comment]
Fixes  #135

**Comment by ganskem** [comment]
Folgende Punkte sind noch anzupassen @palfner-sse 

- Verschieben der Tabs "Lerninhalt" und "Lernkontrolle" auf die rechte Seite (derzeit über den Grunddaten positioniert)
- Einrückung des "Aufgabe hinzufügen" Buttons (Button schließt nicht am Rand rechts ab)
- Positionierung der "Abbrechen" und "Speichern" Buttons (die Buttons sollten dauerhaft sichtbar an der selben Position sein - Hinzufügen eines "Footers")
