### ISSUE TITLE
LiaScript: Build & Upload Proxy Library

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-self-learning#92]
@AlexanWeb built a proxy library to include LiaScript/markdownify without dependencies to Parcel. Open action are:
- [x] Build library with Jenkins
- [x] Upload package to GitHub
- [x] Revise library interface

**Comment by spark-sse** [comment]
**Nice!**

I think some question needs to be answered for this. 
- What features does the library have? 
- What interfaces or data does it use? 
- How we want to integrate the features into selflearn - Is it smart to build this as own library? 

I suggest a small meeting to discuss the way of the selflearn integration. 

> Process update: scheduling of a meeting startet to address these questions

**Comment by Elscha** [comment]
The proxy library can be obtained from https://github.com/orgs/e-Learning-by-SSE/packages/npm/package/nm-liascript-exporter-lib

and used as follows:
```Typescript
import libLiaScr from "@e-learning-by-sse/nm-liascript-exporter-lib/dist/index.js";

function readJsonFile(filePath: string): any {
  try {
    const liaJson = fs.readFileSync(filePath, "utf8");
    return JSON.parse(liaJson);
  } catch (e) {
    console.warn("Error reading file: " + filePath);
    console.warn(e);
    return null;
  }
}

const dataObject = readJsonFile("./src/Minimal.json");

libLiaScr(dataObject)
  .then((doc: string) => {
    console.log("ok", doc);
    fs.writeFileSync("example.md", doc);
  })
  .catch((err: string) => {
    console.warn("err", err);
  });
```

Further parts for improvement (but without a fast solution, yet):
* Revise package structure to make import look like `import libLiaScr from "@e-learning-by-sse/nm-liascript-exporter-lib";` 
* Renaming of Library to use camel case and avoid spell checking errors `import libLiaScr from "@e-learning-by-sse/nm-LiaScript-exporter-lib"`? However, unclear if this is requested for library names
* Rename name of function to something more readable? For instance `liaScriptyfy`?
